site_name: PyMCCE

nav:
    - Overview: index.md
    - For Users:
        - users/install.md
    - For Developers:
        - developers/structure.md
        - developers/flow.md

theme: readthedocs

plugins:
    - markdownmermaid

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js