site_name: PyMCCE

nav:
    - Overview: index.md
    - For Users:
        - users/install.md
        - users/run.md
        - users/ftpl.md
        - users/analyze.md
    - For Developers:
        - developers/structure.md
        - developers/flow.md

theme: readthedocs
